name: Deploy Terraform
on:
  push:
    branches:
      - main
    paths:
      - 's3/**'  # Esto asegura que solo se ejecute cuando haya cambios en archivos dentro de la carpeta 's3'
jobs:
  terraform:
    name: Deploy Terraform Job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_BACKEND }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_BACKEND }}
          aws-region: ${{ secrets.AWS_REGION }}
      # Initialize terraform
      - name: Initialize Terraform
        run: terraform init
      # Execute the terraform plan
      - name: Terraform Plan
        run: terraform plan
      # Deploy terraform changes
      - name: Terraform Apply
        run: terraform apply -auto-approve