name: Destroy Terraform Resources From AWS Organizations (SCPs)
on:
  workflow_dispatch:  # Permite ejecutar el workflow manualmente desde la interfaz de GitHub Actions

jobs:
  terraform:
    name: Destroy Terraform Resources
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_DEPLOY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEPLOY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN_DEPLOY }}
          aws-region: ${{ secrets.AWS_REGION }}
      
      - name: Initialize Terraform
        run: terraform init
        working-directory: ./Organizations-SCP  # Asegúrate de que apunte al directorio correcto

      - name: Terraform Destroy
        run: terraform destroy -auto-approve  # Esto destruirá todos los recursos
        working-directory: ./Organizations-SCP  # Asegúrate de que apunte al directorio correcto