name: Deploy Terraform SCP
on:
  push:
    branches:
      - main
    paths:
      - 'Organizations-SCP/**'  # Solo se ejecuta cuando hay cambios en la carpeta 'Organizations (SCP)'

jobs:
  terraform:
    name: Deploy Terraform Job
    runs-on: ubuntu-latest
    steps:
      # Paso 1: Checkout el código
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      # Paso 2: Configurar las credenciales para la cuenta de despliegue
      # Usamos las credenciales de la cuenta DEPLOY para inicializar Terraform
      - name: Configure AWS credentials for deployment
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_DEPLOY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEPLOY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN_DEPLOY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Paso 3: Inicializar Terraform (con el rol asumido)
      - name: Initialize Terraform
        run: terraform init
        working-directory: ./Organizations-SCP

      # Paso 4: Ejecutar terraform plan (con el rol asumido para acceder al backend)
      - name: Terraform Plan
        run: terraform plan
        working-directory: ./Organizations-SCP

      # Paso 5: Ejecutar terraform apply (con el rol asumido para crear recursos)
      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./Organizations-SCP